name: Front-End Tests & Build

on:
  # Trigger on pushes or pull requests that affect files in the frontend-components folder
  push:
    paths:
      - "frontend-components/**"
  pull_request:
    paths:
      - "frontend-components/**"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository so we can access the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install Dependencies
      - name: Install dependencies
        working-directory: frontend-components/bracket-matcher
        run: npm install

      # Step 4: Run Tests
      - name: Run tests
        working-directory: frontend-components/bracket-matcher
        run: npm test

      # Step 5 (Optional): Build for Production
      - name: Build for production
        working-directory: frontend-components/bracket-matcher
        run: npm run build
